{% set name = "eslint-plugin-react" %}
{% set version = "7.35.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/yannickcr/eslint-plugin-react/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c77362239f88179e79802df85265f1859b9520e36f43e6a34af7a563297b1190

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn <2
    - npmignore
  run:
    - nodejs

test:
  commands:
    - test -d $PREFIX/lib/node_modules/eslint-plugin-react  # [unix]
    - if not exist %LIBRARY_INC%\lib\node_modules\eslint-plugin-react exit 1  # [win]

about:
  home: https://github.com/yannickcr/eslint-plugin-react
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Find and fix problems in your JavaScript code.

extra:
  recipe-maintainers:
    - xhochy
