{% set name = "eslint-plugin-react" %}
{% set version = "7.34.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/yannickcr/eslint-plugin-react/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a31780ac156988b91934a778169682b1a1e8eefff0999f327c89bd32e70f6647

build:
  skip: true  # [win]
  number: 1

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn <2
    - npmignore
  run:
    - nodejs

test:
  commands:
    - test -d $PREFIX/lib/node_modules/eslint-plugin-react  # [unix]
    - if not exist %LIBRARY_INC%\lib\node_modules\eslint-plugin-react exit 1  # [win]

about:
  home: https://github.com/yannickcr/eslint-plugin-react
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Find and fix problems in your JavaScript code.

extra:
  recipe-maintainers:
    - xhochy
